6 semester/python/rebirt2/web/calculator/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index_main, name='calculator'),
    path('create', views.index_create, name='create'),
    path('<int:pk>', views.CalculatorDetailView.as_view(), name='detail_equipment'),
    path('<int:pk>/update', views.CalculatorUpdateView.as_view(), name='update_equipment'),
    path('<int:pk>/delete', views.CalculatorDeleteView.as_view(), name='delete_equipment')
]

6 semester/python/rebirt2/web/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.detail_cart, name='detail_cart'),
    path('add/<int:product_id>', views.add_cart, name='add_cart'),
    path('remove/<int:product_id>', views.remove_cart, name='remove_cart'),

]

6 semester/python/rebirt2/web/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index_main, name='home'),
    path('about', views.index_about, name='about'),
]

6 semester/python/rebirt2/web/web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', 'calculator.urls')),
    path('', include('main.urls')),
    path('news/', include('news.urls')),
    path('calculator/', include('calculator.urls')),
    path('docs/', include('docs.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

6 semester/python/rebirt2/web/calculator/models.py
from django.db import models


class Equipment(models.Model):
    model_img = models.ImageField(upload_to='img/', default="")
    title = models.CharField('Название', max_length=50)
    type = models.CharField('Вид оборудования', max_length=50)
    description = models.TextField('Описание')
    cost = models.CharField('Цена', max_length=50)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/calculator/{self.id}'

    class Meta:
        verbose_name = 'Equipment'
        verbose_name_plural = 'Equipments'

6 semester/python/rebirt2/web/main/models.py
from django.db import models

# Create your models here.

6 semester/python/rebirt2/web/calculator/forms.py
from .models import Equipment
from django.forms import ModelForm, TextInput, Textarea


class EquipmentForm(ModelForm):
    class Meta:
        model = Equipment
        fields = ['id', 'title', 'type', 'description', 'cost']

        widgets = {
            "title": TextInput(attrs={
                'class': 'form-control',
                'placeholder': "Название"
            }),
            "type": TextInput(attrs={
                'class': 'form-control',
                'placeholder': "Тип"
            }),
            "description": Textarea(attrs={
                'class': 'form-control',
                'placeholder': "Описание"
            }),
            "cost": TextInput(attrs={
                'class': 'form-control',
                'placeholder': "Стоимость"
            }),

        }

6 semester/python/rebirt2/web/calculator/views.py
from django.shortcuts import render, redirect

from .forms import EquipmentForm
from .models import Equipment
from django.views.generic import DetailView, UpdateView, DeleteView
import sys

sys.path.append("..")
from cart.forms import CartAddProductForm
def index_main(request):
    equipment = Equipment.objects.all()
    сart_add_equipment_form = CartAddProductForm
    dict_equipment = {'сart_add_equipment_form': сart_add_equipment_form, 'equipment': equipment}

    return render(request, 'calculator/main.html', dict_equipment)


def index_create(request):
    exception = ""
    if request.method == "POST":
        form = EquipmentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
        else:
            exception = "Ошибка формы"

    form = EquipmentForm()
    data = {
        'form': form,
        'exception': exception
    }
    return render(request, "calculator/create.html", data)


class CalculatorDetailView(DetailView):
    model = Equipment
    template_name = 'calculator/details_view.html'
    context_object_name = 'article'


class CalculatorUpdateView(UpdateView):
    model = Equipment
    template_name = 'calculator/create.html'

    form_class = EquipmentForm


class CalculatorDeleteView(DeleteView):
    model = Equipment
    success_url = '../'
    template_name = 'calculator/calculator-delete.html'

6 semester/python/rebirt2/web/main/views.py
from django.shortcuts import render


def index_main(request):
    data_for_main = {
        'title': 'Цель проекта',
        'text': 'Данный сайт создан для помощи пользователям в обзоре и поиске документов по Информационной безопасности'
                 ', а также в подборе нужного оборудования для защиты информационной системы',
    }
    return render(request, 'main/main.html', data_for_main)

def index_about(request):
    return render(request, 'main/about.html')

6 semester/python/rebirt2/web/calculator/templates/calculator/calculator-delete.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title_content %}Удаление статьи{% endblock %}

{% block body_content %}
    <div class="btn_back">
        <a href="#" onclick="history.back();return false;" class="history-back"><i class="fa-solid fa-arrow-left fa-2xl" style="color: #000000;"></i></a>
    </div>
    <h1>Удаление статьи</h1>
    <br>
    <form method="post">
        {% csrf_token %}
        <button class="btn btn-success" type="submit">Удалить статью</button>
        <br>
    </form>
</div>

{% endblock %}

6 semester/python/rebirt2/web/calculator/templates/calculator/create.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title_content %}Оборудование{% endblock %}

{% block body_content %}
<div class="features">
    <div class="btn_back">
        <a href="#" onclick="history.back();return false;" class="history-back"><i class="fa-solid fa-arrow-left fa-2xl" style="color: #000000;"></i></a>
    </div>
    <div class="title_all">
        <h1>Форма по добавлению/изменению оборудования</h1>
    </div>
    <br>
    <form method="post">
        {% csrf_token %}
        {{ form.title }}<br>
        {{ form.type }}<br>
        {{ form.description }}<br>
        {{ form.cost }}<br>
        <span>{{ exception }}</span>
        <button class="btn btn-success" type="submit">Добавить оборудование</button>
        <br>
    </form>
</div>
{% endblock %}

6 semester/python/rebirt2/web/calculator/templates/calculator/details_view.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title_content %}Новости сайта{% endblock %}

{% block body_content %}
<div class="features">
    <div class="btn_back">
        <a href="#" onclick="history.back();return false;" class="history-back"><i class="fa-solid fa-arrow-left fa-2xl" style="color: #000000;"></i></a>
    </div>
    <div class="el_change">
        <div class="img_change">
             <img src="{{ article.model_img.url }}"  object-fit:cover width="100%" height="100%">
        </div>
        <div class="el_text_change">
            <h1>{{ article.title }}</h1>
            <p>Тип: {{ article.type }}</p>
            <p>Стоимость: {{ article.cost }} ₽</p>
        </div>
    </div>
    <div class="el_description">
        <h2>Описание</h2>
        <p>{{ article.description }}</p>
    </div>
</div>
{% endblock %}

6 semester/python/rebirt2/web/calculator/templates/calculator/main.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title_content %}Оборудование{% endblock %}

{% block body_content %}
<div class="features" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
    <div class="btn_back">
        <a href="#" onclick="history.back();return false;" class="history-back"><i class="fa-solid fa-arrow-left fa-2xl" style="color: #000000;"></i></a>
    </div>
    <div class="title_all">
        <h1>Расчет стоимости оборудования</h1>
    </div>
    <br>
    <form action="{% url 'cart:detail_cart' %}" method="post">
        {% csrf_token %}
        {{ detail_cart }}
        <input type="submit" value="Перейти в корзину" class="btn_back_cart">
    </form>
    <br>
    <br>
    {% if equipment %}
    {% for el in equipment %}
    <div class="el_review">
        <div class="img_calc" onclick="location.href='{% url 'detail_equipment' el.id %}';">
            <img src="{{ el.model_img.url }}" object-fit:cover width="100%" height="100%">
        </div>
        <div class="el_text_review" onclick="location.href='{% url 'detail_equipment' el.id %}';">
            <div class="el_title_review">
                <h3>{{ el.title }}</h3>
            </div>
            <p>{{ el.type }}</p>
            <br>
        </div>
        <div class="form_add">
            <form action="{% url 'cart:add_cart' el.id %}" method="post">
                {% csrf_token %}
                {{ сart_add_equipment_form }}
                <input type="submit" value="Добавить">
            </form>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <p>Нет записей</p>
    {% endif %}
</div>
{% endblock %}