6 semester/python/rebirt2/web/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.detail_cart, name='detail_cart'),
    path('add/<int:product_id>', views.add_cart, name='add_cart'),
    path('remove/<int:product_id>', views.remove_cart, name='remove_cart'),

]

6 semester/python/rebirt2/web/web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', 'calculator.urls')),
    path('', include('main.urls')),
    path('news/', include('news.urls')),
    path('calculator/', include('calculator.urls')),
    path('docs/', include('docs.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

6 semester/python/rebirt2/web/cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(label="Количество")
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

6 semester/python/rebirt2/web/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.views.decorators.http import require_POST

import sys
from .cart import Cart
from .forms import CartAddProductForm

sys.path.append("..")
from calculator.models import Equipment


@require_POST
def add_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Equipment, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('calculator')


def remove_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Equipment, id=product_id)
    cart.remove(product)
    return redirect('cart:detail_cart')


def detail_cart(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

6 semester/python/rebirt2/web/cart/templates/cart/detail.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title_content %}Корзина {% endblock %}

{% block body_content %}
<div class="features">
    <div class="btn_back">
        <a href="#" onclick="history.back();return false;" class="history-back"><i class="fa-solid fa-arrow-left fa-2xl" style="color: #000000;"></i></a>
    </div>
    <div class="title_all">
        <h1>Оценка оборудования</h1>
    </div>
        {% for item in cart %}
        {% with product=item.product %}
        <div class="el_cart">
            <div class="img_cart">
                <a href="{{ product.get_absolute_url }}">
                    <img src=" {% if product.model_img %} {{ product.model_img.url }} {% else %} {% static "img/no_image.png" %}
                    {% endif %}" object-fit:cover width="100%" height="100%">
                </a>
            </div>
            <div class="el_text_cart">
                <div class="el_name">
                    <a href="{{ product.get_absolute_url }}"><h3>{{ product.title }}</h3></a>
                    <a href="{% url 'cart:remove_cart' product.id%}" class="btn_delete">Удалить</a>
                </div>
                <div class="el_price">
                    <h2>{{ item.quantity }}</h2>
                    <p>{{ item.cost }} ₽/шт</p>
                </div>
                <div class="el_total_price">
                    <h3>{{ item.total_price }} ₽</h3>
                    <p>&nbsp</p>
                </div>
            </div>
        </div>
        {% endwith %}
        {% endfor %}
        <br>
        <div class="total_cart">
            <h3>Итого: {{ cart.get_total_price }} ₽</h3>
        </div>
</div>
{% endblock %}